### ISSUE TITLE
No music?

### ISSUE THREAD

**Issue by haganaiwa** [ZaneYork/SMAPI-Android-Installer#54]
I have the stardew valley obb file in my obb directory but it still won't play music? Ambient sounds are fine.

**Comment by Mr-Ricatto** [comment]
This problem is most likely not related to smapi, i often meet similar complaints about sound problems from those who play without smapi, and mainly from Huawei users. Is your device not the same brand by any chance? Do you have the same audio problem in the original game (without smapi), or is everything okay?

**Comment by haganaiwa** [comment]
Hello, I'm using a google pixel 3 and the original game has the audio.

**Comment by ZaneYork** [comment]
> Hello, I'm using a google pixel 3 and the original game has the audio.

Which OS version are you on?

**Comment by haganaiwa** [comment]
Android 11

**Comment by ZaneYork** [comment]
> Android 11

Got it, the Android 11 has changed the app private data access policy. No one can access app's data folder except itself, so the patched game cant access the music file, I'll try to handle this situation later (by add a stage to let user grant access to obb file and copy it to external folder)

**Comment by haganaiwa** [comment]
Oh okay thank you!

**Comment by steamboi96** [comment]
Just put atardew valley obb file on android/obb . Congrats your music is  back

**Comment by brinmat** [comment]
Any chance this issue been worked on yet? I have the same issue (Android 11, Samsung S10 Lite). Music works fine in the original app and I have the obb file. (I didn't add it, it was already in the Android folder.)

Or has anyone else found another workaround? The app works beautifully except for the music issue.

**Comment by brinmat** [comment]
Nevermind! You just uploaded a newer version today and it fixed it for me! Thank you!

**Comment by eve-0** [comment]
Hello.
I recently installed SMAPI Installer v3.7.6.9. But the music still doesn't work for some reason, only the ambient sound.  The music works fine in the base game tho.  I also checked the OBB file, it's there.

I'm using Samsung S10+, and it's running Android 11.

**Comment by kyuubimoon** [comment]
Same problem. Use note 20. Ui 3.

**Comment by Hurzhurzhurz** [comment]
Okay, it seems I've found a solution on some Russian torrent site. It seems rather simple and I have no clue why it works. What you need to do is go to your Android/obb directory. There you should be able to see a folder named "com.chucklefish.stardewvalley". In this folder you'll find the necessary obb file with all the music. Now you have to copy the file, go back to Android/obb, create another folder named "com.zane.stardewvalley" and paste the file into the new folder. That seems to have done the trick.

**Comment by StarGazer021** [comment]
I am having the same problem with the music. Android 5 
Stardew Valley
V 1.4.151
com.chucklefish.stardewvally.obb file where it should be but still no music.
Any thoughts? Ideas?

**Comment by eve-0** [comment]
> Okay, it seems I've found a solution on some Russian torrent site. It seems rather simple and I have no clue why it works. What you need to do is go to your Android/obb directory. There you should be able to see a folder named "com.chucklefish.stardewvalley". In this folder you'll find the necessary obb file with all the music. Now you have to copy the file, go back to Android/obb, create another folder named "com.zane.stardewvalley" and paste the file into the new folder. That seems to have done the trick.

Reply:
THIS WORKS
I LOVE YOU HOLY SHIT

**Comment by eve-0** [comment]
> Okay, it seems I've found a solution on some Russian torrent site. It seems rather simple and I have no clue why it works. What you need to do is go to your Android/obb directory. There you should be able to see a folder named "com.chucklefish.stardewvalley". In this folder you'll find the necessary obb file with all the music. Now you have to copy the file, go back to Android/obb, create another folder named "com.zane.stardewvalley" and paste the file into the new folder. That seems to have done the trick.

Reply:
I LOVE YOU.
The "com.zane.stardewvalley" folder method WORKS! FINALLY.

**How to fix the in-game music:**

1. ➜ Android ➜ OBB
2. **Create** a folder named "com.zane.stardewvalley"
3. **Open** "com.chucklefish.stardewvalley" and **copy** the .obb file.
4. **Paste** the .obb file in "com.zane.stardewvalley"
DONE!

**Comment by NalgeneOrange** [comment]
Halp!  I downloaded 3.7.6.9, but when I install it, it shows the running version as 3.7.6.1.  What the heck?  I don't even have 3.7.6.1 installed anywhere - I just powerwashed my Chromebook, enabled Linux/ADB and installed this version of SMAPI.  Anyone else seeing this?   Would love to have music *and* mods :)

**Comment by steveluong** [comment]
> Halp! I downloaded 3.7.6.9, but when I install it, it shows the running version as 3.7.6.1. What the heck? I don't even have 3.7.6.1 installed anywhere - I just powerwashed my Chromebook, enabled Linux/ADB and installed this version of SMAPI. Anyone else seeing this? Would love to have music _and_ mods :)

same issue. downloaded 3.7.6.9 but shows 3.7.6.1 after installed. still no music

**Comment by CrystalliumX** [comment]
Help, i installed latest SMAPI version, checked obb/com.zane.stardewvalley. There is already cache file named main.105.com.chucklefish.stardewvalley.obb here. But music in modded Stardew Valley still doesn't work.

**Comment by ruthlessearl** [comment]
> Okay, it seems I've found a solution on some Russian torrent site. It seems rather simple and I have no clue why it works. What you need to do is go to your Android/obb directory. There you should be able to see a folder named "com.chucklefish.stardewvalley". In this folder you'll find the necessary obb file with all the music. Now you have to copy the file, go back to Android/obb, create another folder named "com.zane.stardewvalley" and paste the file into the new folder. That seems to have done the trick.

Ok.. earlier, this tricks just shown from someone i have asked about music issues to me.. and when im doing that tricks, yuh the obb of stardew 1.4.5.151 is there also the related Stardew apk on it, and i also installed smapi stardew valley 3.7.6 that it says in the notes that it required 1.4.5.148 Stardew valley to work well.. 
And.. when im about to make a folder named "com.zane.stardewvalley" on the Android/OBB, main while after I've done making new folder... IT AUTOMATICALLY PASTE THE OBB THAT I HAVE THERE the obb file from the folder named with 'com,chucklefish.stardewvalley"... AND ITS FREAKING ME UP...

so now.. i have not copied the main obb and paste it into zane folder because it paste automatically it self... 

But...



Still not working, no music, ambients sounds is unsettled to each season related, even at night birds are still tweeting.. Like.. "Ogh what now!!?.. another problem!!"
It freaking me up, im so sick if it.. 😭😭😭 how is this happen to me while other fixed it correctly in android 11.. yuh mine in android 11 to but why is this.. oh god😭😭😭
All i jusy want is to enjoy Stardew with mods i like and corrected ambients sounds and music..😭😭😭😭

**Comment by lividhen** [comment]
> 
> 
> >
> All i jusy want is to enjoy Stardew with mods i like and corrected ambients sounds and music..😭😭😭😭

You could try using the custom music mod and just put the OST in. I'm not sure which version works on the current version of smapi on android if any but it could be worth a shot.

**Comment by ruthlessearl** [comment]
> Nevermind! You just uploaded a newer version today and it fixed it for me! Thank you!

Hey how did it work on you, mine i install that last version release but it did not install the Smapi Stardew valley, i already have a main version of SDV  but still did not install, ot says unavailable to log in, contact developer.

**Comment by ruthlessearl** [comment]
> the

What the.. even a music has its mods to work?? 
Ahmm thanks for that, ill try on it, ill back here when it work well, i hope 😳

**Comment by ruthlessearl** [comment]
> > > 
> > 
> > 
> > All i jusy want is to enjoy Stardew with mods i like and corrected ambients sounds and music..😭😭😭😭
> 
> You could try using the custom music mod and just put the OST in. I'm not sure which version works on the current version of smapi on android if any but it could be worth a shot.

I think I've already done trying it, but i dont like it sorry 😅
The sounds of bird that only playing without obb is still in it even at night, and also the gus saloon joke box has no music..
What is this OST anyway maybe that something to do with it

**Comment by ZaneYork** [comment]
Try latest 3.7.6.10

**Comment by Alexx879** [comment]
Solution: all you have to do is just install basic game with obb then install smapi stardew valley then move from "com.chucklefish.stardewvalley" to "com.zane.stardewvalley".it's worked for me:)

Btw sorry for my lack of English

**Comment by avylol08** [comment]
Can someone help me figure out what an obb is and where to find it? I feel utterly hopeless 😭

**Comment by ankithost** [comment]
> I have the stardew valley obb file in my obb directory but it still won't play music? Ambient sounds are fine.

I have the method.
I'm also on android 11 so I don't know if it will work for 12.
I just deleted the base game and made the obb folder with the same name (com.chucklefish.stardewvalley)
And put the obb into it and it worked.
I used x-plore to access obb folder.

**Comment by ankithost** [comment]
I have the method.
I'm also on android 11 so I don't know if it will work for 12.
I just deleted the base game and made the obb folder with the same name (com.chucklefish.stardewvalley)
And put the obb into it and it worked.
I used x-plore to access obb folder.

**Comment by ankithost** [comment]
> > Android 11
> 
> Got it, the Android 11 has changed the app private data access policy. No one can access app's data folder except itself, so the patched game cant access the music file, I'll try to handle this situation later (by add a stage to let user grant access to obb file and copy it to external folder)

I have the method.
I'm also on android 11 so I don't know if it will work for 12.
I just deleted the base game and made the obb folder with the same name (com.chucklefish.stardewvalley)
And put the obb into it and it worked.
I used x-plore to access obb folder.

I'm sorry if it looks like spam I'm just so excited to have finally fixed it.

**Comment by gerasiovM** [comment]
I've been tinkering with this issue this whole evening, because none of the solutions worked on my Android 11 phone. What i did:
1. Uninstalled SMAPI Stardew Valley
2. Created the com.zane.stardewvalley and put the obb file inside
3. Pressed install in the SMAPI Installer AND when prompted with the window to choose which files should SMAPI Installer be able to access chose the com.zane.stardewvalley folder.
4. Opened the game

If none of this works try tinkering with the cache of the game, because that might affect it.

**Comment by bayuhamka** [comment]
You just need to copy, remember not cut .obb file
But copy a file .obb , so you have double obb (original and zane) com.zane.stardewvalley and based obb file folder com.cuchklefish.stardew it will be fixed your problems. I just doing that and it works

**Comment by LubnaRL** [comment]
Where did you guys install from? I am having the same problem. Please help!
